import {
  demoBalanceConfigSeedRows,
  demoCardSeedRows,
} from "../game/runtime";
import {
  createEnumStatements,
  createIndexStatements,
  createTableStatements,
} from "./schema";

const jsonLiteral = (value: unknown) => {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
};

const textLiteral = (value: string | null | undefined) => {
  if (value === null || value === undefined) {
    return "NULL";
  }

  return `'${value.replace(/'/g, "''")}'`;
};

const numberLiteral = (value: number | null | undefined) => {
  if (value === null || value === undefined) {
    return "NULL";
  }

  return String(value);
};

const booleanLiteral = (value: boolean) => (value ? "TRUE" : "FALSE");

const cardInsertStatements = demoCardSeedRows.map((row) => `
INSERT INTO cards (
  id,
  slug,
  title,
  body,
  phase,
  category,
  card_type,
  character_id,
  stress_level,
  trigger_type,
  trigger_probability,
  route_tags,
  requirements,
  choices,
  weight,
  priority,
  cooldown_turns,
  once_per_run,
  repeatable,
  min_pressure,
  max_pressure,
  educational_tags,
  learning_goal,
  misconception_tag,
  guide_entry_id,
  set_flags,
  remove_flags,
  followup_arc,
  meta,
  published
)
VALUES (
  ${textLiteral(row.id)},
  ${textLiteral(row.slug)},
  ${textLiteral(row.title)},
  ${textLiteral(row.body)},
  ${textLiteral(row.phase)},
  ${textLiteral(row.category)},
  ${textLiteral(row.cardType)},
  ${textLiteral(row.characterId)},
  ${textLiteral(row.stressLevel)},
  ${textLiteral(row.triggerType)},
  ${numberLiteral(row.triggerProbability)},
  ${row.routeTags ? jsonLiteral(row.routeTags) : "NULL"},
  ${row.requirements ? jsonLiteral(row.requirements) : "NULL"},
  ${jsonLiteral(row.choices)},
  ${numberLiteral(row.weight)},
  ${numberLiteral(row.meta?.priority ?? 0)},
  ${numberLiteral(row.meta?.cooldownTurns ?? 0)},
  ${booleanLiteral(row.oncePerRun)},
  TRUE,
  ${numberLiteral(row.meta?.minPressure)},
  ${numberLiteral(row.meta?.maxPressure)},
  ${row.meta?.educationalTags ? jsonLiteral(row.meta.educationalTags) : "NULL"},
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  ${row.meta ? jsonLiteral(row.meta) : "NULL"},
  ${booleanLiteral(row.published)}
)
ON CONFLICT (id) DO UPDATE
SET
  slug = EXCLUDED.slug,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  phase = EXCLUDED.phase,
  category = EXCLUDED.category,
  card_type = EXCLUDED.card_type,
  character_id = EXCLUDED.character_id,
  stress_level = EXCLUDED.stress_level,
  trigger_type = EXCLUDED.trigger_type,
  trigger_probability = EXCLUDED.trigger_probability,
  route_tags = EXCLUDED.route_tags,
  requirements = EXCLUDED.requirements,
  choices = EXCLUDED.choices,
  weight = EXCLUDED.weight,
  priority = EXCLUDED.priority,
  cooldown_turns = EXCLUDED.cooldown_turns,
  once_per_run = EXCLUDED.once_per_run,
  repeatable = EXCLUDED.repeatable,
  min_pressure = EXCLUDED.min_pressure,
  max_pressure = EXCLUDED.max_pressure,
  educational_tags = EXCLUDED.educational_tags,
  meta = EXCLUDED.meta,
  published = EXCLUDED.published,
  updated_at = NOW();
`);

const balanceConfigStatements = demoBalanceConfigSeedRows.map((row) => `
INSERT INTO balance_configs (
  key,
  value,
  description
)
VALUES (
  ${textLiteral(row.key)},
  ${jsonLiteral(row.value)},
  ${textLiteral(row.description)}
)
ON CONFLICT (key) DO UPDATE
SET
  value = EXCLUDED.value,
  description = EXCLUDED.description,
  updated_at = NOW();
`);

export const buildSupabaseSeedSql = () => {
  return [
    "-- Generated by src/db/sqlExport.ts",
    "-- Safe to run in Supabase SQL Editor",
    "BEGIN;",
    ...createEnumStatements.map((statement) => statement.trim()),
    ...createTableStatements.map((statement) => statement.trim()),
    ...createIndexStatements.map((statement) => statement.trim()),
    ...cardInsertStatements.map((statement) => statement.trim()),
    ...balanceConfigStatements.map((statement) => statement.trim()),
    "COMMIT;",
    "",
  ].join("\n\n");
};
